# Generated by Django 3.2.9 on 2021-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=50)),
                ('itemPrice', models.FloatField(max_length=10)),
                ('itemDescription', models.CharField(max_length=300)),
                ('itemCategory', models.CharField(default='pizza', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('emailAddress', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(default='none', max_length=500)),
                ('itemName', models.CharField(max_length=500)),
                ('itemPrice', models.FloatField(max_length=10)),
                ('quantity', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
