# Generated by Django 3.2.9 on 2021-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backsideapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordertable',
            name='emailAddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
