# Generated by Django 3.2.9 on 2021-12-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backsideapi', '0002_auto_20211215_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordertable',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='itemPrice',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='quantity',
            field=models.CharField(max_length=150),
        ),
    ]
