# Generated by Django 3.2.9 on 2021-12-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backsideapi', '0004_alter_newordertable_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordertable',
            name='itemName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backsideapi.menuitem'),
        ),
    ]
