# Generated by Django 3.2.9 on 2021-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backsideapi', '0005_alter_newordertable_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordertable',
            name='address',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='itemName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='itemPrice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='newordertable',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
